### ISSUE TITLE
Possible bug found at pyWAD/pluginresults.py

### ISSUE THREAD

**Issue by jhuguetn** [wadqc/WAD_Python#7]
addBool() method at pluginresults.py file is currently calling addResult() generic function to store boolean results in XML file, labeling result as 'bool': 

```
self._addResult('boolean', description, value_str, level, quantity, units)
```

While AnalyseModuleResultFile.java method parseDocument() which checks the XML output file created by WAD_Python is checking for results with type equal to 'boolean':

```
} else if (type.equals("boolean")){
                    ResultsBoolean result = new ResultsBoolean();
                    result.setType(type);
```

This mismatching causes boolean results not to be propagated from XML to wadWC database.

Jordi

**Comment by asch99** [comment]
Strange, that was an issue which has been fixed some time ago. The issue you describe does not exist anymore in the current version of WAD_Python. Also it does not exist in your description above...
